name: CI-macOS

# Triggers the workflow on pull request event for the main branch
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is responsible for building and testing the macOS project
  build-and-test:
    # Specifies the type of runner to execute the job
    runs-on: self-hosted

    # Sets a timeout for the job to prevent it from running indefinitely
    timeout-minutes: 8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out the repository under $GITHUB_WORKSPACE, so our job can access it
    - uses: actions/checkout@v2

    # Selects the appropriate Xcode version installed on the self-hosted runner
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    # Builds and tests the macOS project using Xcode
    - name: CI_macOS build and test
      run: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI_macOS" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES